Tkt 00184 - Update header layout
NHSLeadership/nightingale pull request #185
Opened 2018-01-29 13:23 UTC by Android63

Updated header from this:
![screen shot 2018-01-29 at 13 12 34](https://user-images.githubusercontent.com/1991226/35512016-28142780-04f6-11e8-839f-0c2d13506242.png)

To this:
![screen shot 2018-01-29 at 13 14 31](https://user-images.githubusercontent.com/1991226/35512097-614ac626-04f6-11e8-8e83-40a8ea705849.png)

The main differences are:

1. The search bar is optional but, if present, is 100% of its container width and doesn't push the menu bar down.
2. The menu bar is left-aligned in its container
3. The login button, if present, is right-aligned in its container.

Tested in various browsers, including mobile. In some older browsers, the mobile view is used (which is a reasonable failsafe).

2018-02-02 09:22 UTC, cehwitham requested changes

2018-02-02 09:22 UTC, cehwitham commented on components/nav-primary/_components.nav-primary.scss
> +    margin-top: $global-border-mid+36;
Where does the 36 come from here @Android63?

2018-02-02 09:22 UTC, cehwitham commented on components/search-bar/_components.search-bar.scss
> +     height: 36px;
Has this always been a fixed height?

2018-02-02 09:22 UTC, cehwitham commented on components/search-bar/_components.search-bar.scss
> +       margin-bottom: -36px;
@csswizardry any thoughts on this? Is this the best way to accomplish this?

2018-02-02 09:22 UTC, cehwitham commented on index.html
> +        <img src="./assets/img/logos/NHS_LA_Logo_Blue.png" alt="NHS Leadership Academy" class="c-page-header__logo" />
@Android63 should we have a more standardised filenaming convention for images? Seems we're switching between - and _ and caps?

2018-02-02 12:10 UTC, Android63 commented on components/nav-primary/_components.nav-primary.scss
> +    margin-top: $global-border-mid+36;
It's the height of the search bar (which has a bottom margin of -36px to cancel this out). I've added a comment to that effect.

2018-02-02 12:13 UTC, Android63 commented on components/search-bar/_components.search-bar.scss
> +     height: 36px;
I think so. The height has to match the NHS lozenge in the logo. I've added a comment to that effect.

2018-02-02 12:15 UTC, Android63 commented on index.html
> +        <img src="./assets/img/logos/NHS_LA_Logo_Blue.png" alt="NHS Leadership Academy" class="c-page-header__logo" />
Agreed. This is addressed in https://github.com/NHSLeadership/nightingale/pull/179

2018-02-05 13:01 UTC, Android63 commented
Are you OK with me merging this in @cehwitham? I will ask Harry to review, but I'd like to get the functionality in place for now and correct any issues he raises later.

2018-02-19 10:05 UTC, csswizardry commented on components/search-bar/_components.search-bar.scss
> +       margin-bottom: -36px;
This is gonna be an interesting one to solve! Let’s discuss :)

2018-02-19 10:55 UTC, Android63 commented on components/search-bar/_components.search-bar.scss
> +       margin-bottom: -36px;
Looking forward to it :)

2018-03-23 12:19 UTC, Android63 commented
@cehwitham I've checked this locally and it looks fine. Could you review it with a view to a merge please?

2018-03-26 10:57 UTC, cehwitham approved these changes

2018-03-26 11:23 UTC, merged