Tkt 00199 - information card
NHSLeadership/nightingale pull request #210
Opened 2018-04-09 10:37 UTC by Android63

MVP information card without media or accordion dropdown for now.

![screen shot 2018-04-09 at 11 36 36](https://user-images.githubusercontent.com/1991226/38493492-4c968122-3bea-11e8-865c-1f8f1a326138.png)

2018-04-10 09:18 UTC, Android63 commented
Please note that, since the markup and styling is almost identical for alerts and information cards, I have merged #200 into #199

2018-04-11 13:34 UTC, cehwitham reviewed
Feels like there's a bit of confusion with the paragraph component and we just need to clear up how we want to implement that?

2018-04-11 13:34 UTC, cehwitham commented on components/paragraphs/_components.paragraphs.scss
> +.c-paragraph--supporting {
@Android63 is this used in multiple places or should this be achieved with a Mix?

2018-04-11 15:03 UTC, Android63 commented
@cehwitham I've simplified this by using the <small> element rather than a distinct supporting paragraph style. Could you review again please?

2018-04-11 15:26 UTC, cehwitham requested changes
Much better, just a small tweak needed.

2018-04-11 15:26 UTC, cehwitham commented on settings/_settings.definitions.scss
> +  'alert': #DA291C,
Watch capitalisation in values.

2018-05-01 14:43 UTC, Android63 commented
@cehwitham I've fixed the capitalisation but I wonder if we need $color-alert at all since it's identical to $color-error. What do you think @Pro-Paul?

2018-05-08 10:18 UTC, Pro-Paul commented
@Android63 We will need to review what error, alert states we have and what level of urgency they are so we can then colour code them moving forward. But for now I think we can just stick with the initial alert and should we need to expand that we can. @cehwitham would you agree?

2018-05-08 13:15 UTC, Android63 commented
So Use same colour for both alerts and warnings.

2018-05-10 09:34 UTC, Android63 commented
@cehwitham could you review this again please?

2018-05-10 09:40 UTC, cehwitham approved these changes

2018-05-10 09:53 UTC, merged