Txt 00209
NHSLeadership/nightingale pull request #211
Opened 2018-04-10 11:59 UTC by Pro-Paul

Updated Headings to correct sizing and added specific line heights. Also added missing H6. Ready to be merged into develop branch on code approval.

2018-04-10 12:23 UTC, cehwitham reviewed
Is  there a need to introduce all the line heights @Pro-Paul ? We didn't have this currently?

2018-04-11 08:16 UTC, Pro-Paul commented
We didn't have the line heights set, they were all generic so they have now been set, I will be doing the same for body copy as they also have not been set according to prior design format.

2018-04-11 13:40 UTC, cehwitham requested changes
Do we not already have a relative method for handling line heights? We shouldn't really be using exact values for line heights as it's not best practice.

https://csswizardry.com/2012/11/code-smells-in-css/#hard-codedabsolute-values

2018-04-11 14:12 UTC, Pro-Paul commented
I might need some help to talk through what needs to be updated and how in the code for this one @cehwitham

2018-04-11 14:15 UTC, cehwitham commented
Probably one to visit with @csswizardry

2018-08-13 09:01 UTC, cehwitham commented on tools/_tools.mixins.scss
>      line-height: ceil($font-size / $global-line-height) * ($global-line-height / $font-size);
Won't this always = 1? Should one of the variables be a different font size? Global or something?

2018-08-13 09:52 UTC, csswizardry commented on tools/_tools.mixins.scss
>      line-height: ceil($font-size / $global-line-height) * ($global-line-height / $font-size);
The `ceil()` rounds up the first equation so it will always be >=1 👍

2018-08-13 10:51 UTC, cehwitham commented on tools/_tools.mixins.scss
>      line-height: ceil($font-size / $global-line-height) * ($global-line-height / $font-size);
Ah I'd missed the middle set of brackets.

2018-08-13 14:05 UTC, csswizardry approved these changes
Worked on this with @Pro-Paul; we’re both happy with it.

2018-08-14 08:58 UTC, cehwitham approved these changes

2018-08-14 09:02 UTC, merged